// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxjzmnjrugieelegyabn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4anptbmpydWdpZWVsZWd5YWJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5OTkyNzEsImV4cCI6MjA2NjU3NTI3MX0.f8Pf4uXBahYhhpYr4s-jbLH3VEhP_8o_8Hv2olk9A6E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);